#!/bin/bash
set -e

mysql -u root -p"${MYSQL_ROOT_PASSWORD}" <<-EOSQL
    CREATE DATABASE IF NOT EXISTS authentication_db;
    CREATE DATABASE IF NOT EXISTS user_profile_db;

    CREATE USER IF NOT EXISTS '${AUTH_DB_USERNAME}'@'%' IDENTIFIED BY '${AUTH_DB_PASSWORD}';
    GRANT ALL PRIVILEGES ON authentication_db.* TO '${AUTH_DB_USERNAME}'@'%';

    CREATE USER IF NOT EXISTS '${PROFILE_DB_USERNAME}'@'%' IDENTIFIED BY '${PROFILE_DB_PASSWORD}';
    GRANT ALL PRIVILEGES ON user_profile_db.* TO '${PROFILE_DB_USERNAME}'@'%';

    FLUSH PRIVILEGES;
EOSQL
